# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

steps:
- bash: |
    npm install 
    npm run build --if-present
    npm prune --production
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(036f82dc-170c-4faf-999e-a5f08655b838)'
    appType: 'functionApp'
    appName: 'spaceapi-astronauts-service'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'zipDeploy'
